### ISSUE TITLE
v0.10 checklist

### ISSUE THREAD

**Issue by aaronrudkin** [aaronrudkin/autumn#1]
Things to do before v0.10:
- [ ] Code: Complete Spencer design effects
- [ ] Vignette: Specifying targets
- [ ] Vignette: Convergence criteria
- [ ] Vignette: Error functions
- [ ] Vignette: Variable selection functions
- [ ] Vignette: Speed, memory, and convergence benchmarks
- [ ] Vignette: Design effects
- [ ] Tests: Design effects
- [ ] Tests: Code coverage for various convergence methods
- [ ] Examples and documentation: Design effects
- [ ] Check included data for desirable performance
- [ ] Fix vignette note in README
- [ ] Fix CODE OF CONDUCT
- [ ] News
- [ ] cran-comments.md
- [ ] Test binary package
- [ ] GitHub release
